{
 "title": "Namespace Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Memory Limit",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(scalar(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\",type=\"used\"}) / scalar(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.memory\",type=\"hard\"}))* 100"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(scalar(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.cpu\",type=\"used\"}) / scalar(kube_resourcequota{namespace=\"$namespace\",resource=\"limits.cpu\",type=\"hard\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(scalar(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\",type=\"used\"}) / scalar(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.cpu\",type=\"hard\"})) * 100",
     "legendFormat": "CPU Request"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(scalar(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.memory\",type=\"used\"}) / scalar(kube_resourcequota{namespace=\"$namespace\",resource=\"requests.memory\",type=\"hard\"})) * 100"
    }
   ]
  }
 ]
}