{
 "title": "Usage of memory/cpu usage of Containers",
 "description": "Usage of memory/cpu usage of Containers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container!=\"POD\"},namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container!=\"POD\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(count({container=\"$container\", namespace=\"$namespace\"}) by (node))",
     "legendFormat": "nodes"
    }
   ]
  },
  { "title": "Usage relative to limit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Relative Cpu usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\"}[60s])) / sum(container_spec_cpu_quota{container=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container=\"$container\", namespace=\"$namespace\"})",
     "legendFormat": "relative to limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\"}[60s])) / sum(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"} / 1024) / count(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"})",
     "legendFormat": "relative to request"
    }
   ]
  },
  {
   "title": "Relative memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"})/ sum(container_spec_memory_limit_bytes{container=\"$container\", namespace=\"$namespace\"})",
     "legendFormat": "relative to limit"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$container\"})",
     "legendFormat": "relative to requested"
    }
   ]
  },
  { "title": "Usage per pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Cpu usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\"}[60s])) by (id,pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container) / count(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (id, pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (container,namespace)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$container\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$container\"})",
     "legendFormat": "requested"
    }
   ]
  },
  { "title": "Usage per pod (average)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Cpu usage (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\"}[60s])) by (namespace,container) / count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container) / count(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) / count(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$container\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$container\"})",
     "legendFormat": "requested"
    }
   ]
  },
  { "title": "Usage total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Cpu usage (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\"}[60s])) by (namespace,container)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=\"$container\", namespace=\"$namespace\"} / container_spec_cpu_period{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{container=\"$container\", namespace=\"$namespace\"}) by (namespace,container)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$container\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time percentiles",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "native | 0.50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(nginx_http_request_duration_seconds_bucket{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,le))",
       "legendFormat": "nginx | 0.50"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(http_requests_total{app=\"$container\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app,code)",
       "legendFormat": "native | {{code}}"
      },
      {
       "expr": "sum(irate(nginx_http_requests_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app,status)",
       "legendFormat": "nginx | {{status}}"
      },
      {
       "expr": "sum(irate(haproxy_backend_http_responses_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace,code)",
       "legendFormat": "haproxy | {{code}}"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_backend_http_responses_total{app=\"$container\", kubernetes_namespace=\"$namespace\",code=\"5xx\"}[30s])) by (app,kubernetes_namespace) / sum(irate(haproxy_backend_http_responses_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (app,kubernetes_namespace)",
       "legendFormat": "haproxy"
      },
      {
       "expr": "sum(irate(http_requests_total{app=\"$container\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\", code=~\"5[0-9]+\"}[30s])) by (kubernetes_namespace,app) / sum(irate(http_requests_total{app=\"$container\", handler!=\"prometheus\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app)",
       "legendFormat": "native"
      },
      {
       "expr": "sum(irate(nginx_http_requests_total{app=\"$container\", kubernetes_namespace=\"$namespace\", status=~\"5[0-9]+\"}[30s])) by (kubernetes_namespace,app) / sum(irate(nginx_http_requests_total{app=\"$container\", kubernetes_namespace=\"$namespace\"}[30s])) by (kubernetes_namespace,app)",
       "legendFormat": "nginx"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage relative to request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage (relative to request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_system_seconds_total{container=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container) / sum(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container)",
       "legendFormat": "system"
      },
      {
       "expr": "sum(irate(container_cpu_user_seconds_total{container=\"$container\", namespace=\"$namespace\"}[30s])) by (namespace,container) / sum(container_spec_cpu_shares{container=\"$container\", namespace=\"$namespace\"} / 1024) by (namespace,container)",
       "legendFormat": "user"
      }
     ]
    }
   ]
  }
 ]
}